[package]
name = "influxdb"
version = "0.0.5"
authors = ["Gero Gerke <11deutron11@gmail.com>"]
edition = "2018"
description = "InfluxDB Driver for Rust"
keywords = ["influxdb", "database", "influx"]
license = "MIT"
readme = "README.md"
include = ["src/**/*", "tests/**/*", "Cargo.toml", "LICENSE"]
repository = "https://github.com/Empty2k12/influxdb-rust"

[badges]
travis-ci = { repository = "Empty2k12/influxdb-rust", branch = "master" }

[dependencies]
chrono = { version = "0.4.10", optional = true }
failure = "0.1.6"
futures = "0.3.1"
reqwest = { git = "https://github.com/seanmonstar/reqwest", rev = "09e7fe6", features = ["json"]}
serde = { version = "1.0.104", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }

[features]
use-serde = ["serde", "serde_json"]
chrono_timestamps = ["chrono"]
default = ["use-serde"]

[dev-dependencies]
tokio = { version = "0.2.6", features = ["macros"] }
